name: Build main (CI) [Linux/Windows]

on:
  push:
    branches: [ "main", "dev/menu" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -S ${{github.workspace}} -Wno-dev

    - name: Make
      working-directory: ${{github.workspace}}/build
      run: make -j 4

  build-win:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3

    - name: CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -S ${{github.workspace}} -G "MinGW Makefiles" -Wno-dev

    - name: Make
      working-directory: ${{github.workspace}}/build
      run: mingw32-make -j 4
